issues:
    exclude-rules:
        - linters:
              - gosimple
          text: "S1039:"

        # Exclude issues bypassing staticcheck.conf
        - linters:
              - staticcheck
          text: "SA1019:"

        - linters:
              - unparam
          text: "always receives"

    max-per-linter: 0
    max-same-issues: 0

linters:
    disable-all: true
    enable:
        - errcheck
        - gofmt
        - gocritic
        - gocognit
        - gosimple
        - ineffassign
        - misspell
        - nakedret
        - staticcheck
        - unconvert
        - goimports
        - unused
        - unparam
        - vet
        - gosec

run:
    timeout: 10m
    skip-dirs:
        - github.com/inclusi-blog
    skip-files:
        - ".*(_test.go)$"
    mod: readonly